### ISSUE TITLE
Could you explain how to get sid cookie?

### ISSUE THREAD

**Issue by Whitesttax** [kampffrosch94/jpdb-connect#14]
Not sure how to do that, if you could add it to the FAQ, it'd be great! 
Also, the option for duplicate detection only shows up if you have Advanced turned on for yomichan settings, might want to add that on the setup page.

**Comment by kampffrosch94** [comment]
It depends a bit on your browser. For firefox hit F12 to open the developer console while on jpdb.io. In the storage tab you'll find your cookies for your current site.
![image](https://user-images.githubusercontent.com/10487586/214139138-6bf9b91a-1eb5-41f8-a323-ac43f17ee14a.png)

You are right about the advanced settings, I should mention that.

**Comment by kampffrosch94** [comment]
I'll switch this project to the jpdb api when its published which should make the setup a bit easier. Also might allow me to implement the duplicate detection part.

**Comment by Whitesttax** [comment]
Thanks, it's working now :)
